### ISSUE TITLE
Feedback for v3 mobile interactions and copy

### ISSUE THREAD

**Issue by timoguin** [tiki/tiki.github.io#97]
A few quick screenshots with QA feedback for the new v3 release. 

## Screenshots

Copy idea:

![Screenshot_20221104-224131.png](https://user-images.githubusercontent.com/671968/200099875-0407adb7-bb44-4713-acb8-b123c9c991aa.png)

Interactivity:

![Screenshot_20221104-224513.png](https://user-images.githubusercontent.com/671968/200099889-3581e305-6001-4134-b482-051f62eec9b1.png)

![Screenshot_20221104-224655.png](https://user-images.githubusercontent.com/671968/200099895-490560b8-9d9a-4e4d-833f-9ade97d4ec46.png)

![Screenshot_20221104-224917.png](https://user-images.githubusercontent.com/671968/200099900-26576b58-e4cd-4ca2-9c14-5fa29bbb2463.png)

**Comment by mike-audi** [comment]
The "fuck" part has already been removed. See [3.0.2](https://github.com/tiki/tiki.github.io/releases/tag/3.0.2).

ctrl + click still to be fixed.

**Comment by mike-audi** [comment]
Get in touch button comment has been moved to #98

**Comment by mike-audi** [comment]
To fix the ctrl+click issue requires moving the UtilsBtnCmp from <button> tag to <a> tag

**Comment by mike-audi** [comment]
fixed in https://github.com/tiki/tiki.github.io/releases/tag/3.0.5
